### ISSUE TITLE
Decide how to deal with vocabulary files

### ISSUE THREAD

**Issue by tompollard** [xborrat/medical-standard-voc-translator#6]
The package requires standardized vocabulary files downloaded from the OHDSI website:
https://www.ohdsi.org/analytic-tools/athena-standardized-vocabularies/

We could:
- Incorporate the files into the package. The size of the files might make this problematic and we would need follow the terms of the licenses.
- Provide a helper function to download the files. The function could download the files directly from the OHDSI website or we could keep a copy of the files elsewhere.

**Comment by tompollard** [comment]
The total compressed file of the default set of vocabulary files is 920MB. The compressed size of CONCEPT_RELATIONSHIP.csv (which seems to be the most important file) is 265MB.  The uncompressed size of CONCEPT_RELATIONSHIP.csv is 2.3GB.

Nice discussion of some possible solutions here:
https://www.dampfkraft.com/code/distributing-large-files-with-pypi.html

It looks like including the files within the package isn't really an option (the max file size is 60MB) so we can either download the files upon installation or provide a helper function for downloading the files.

**Comment by xborrat** [comment]
Let's stick with the second option. Choosing only two dictionaries yields two files of 220MB and 177MB. To keep the package "multi-vocabulary" with the first option, we should download a large file, maybe 2Gb, which won't be updated until we download an updated version and update the package from it.  
In the second option if we download the files from ATHENA we will obtain the updated vocabularies but if they change the athena webapp and there's no API the package won't work.  The other option of downloading a dictionary with all the vocabularies (2Gb or more), saving it to a server, and using a filter to select the needed vocabularies may work but we will need to update the "mega dictionary"  periodically(maybe this can be automated...).

**Comment by tompollard** [comment]
> In the second option if we download the files from ATHENA we will obtain the updated vocabularies but if they change the athena webapp and there's no API the package won't work. The other option of downloading a dictionary with all the vocabularies (2Gb or more), saving it to a server, and using a filter to select the needed vocabularies may work but we will need to update the "mega dictionary" periodically(maybe this can be automated...).

I agree, offering an option for downloading the files seems best. Should we post a message at https://forums.ohdsi.org/c/implementers/6 to ask whether there is a persistent link for the files and, if not, whether they mind us hosting them on PhysioNet or GitHub?

**Comment by tompollard** [comment]
After requesting the files, they send an email with a link to download them:

```
ALL Vocabularies:
--
ICD10CM | - | International Classification of Diseases, Tenth Revision, Clinical Modification (NCHS)
NUCC | - | National Uniform Claim Committee Health Care Provider Taxonomy Code Set (NUCC)
Revenue Code | - | UB04/CMS1450 Revenue Codes (CMS)
LOINC | - | Logical Observation Identifiers Names and Codes (Regenstrief Institute)
SNOMED | - | Systematic Nomenclature of Medicine - Clinical Terms (IHTSDO)
Gender | - | OMOP Gender
NDC | - | National Drug Code (FDA and manufacturers)
RxNorm Extension | - | RxNorm Extension (OHDSI)
SPL | - | Structured Product Labeling (FDA)
RxNorm | - | RxNorm (NLM)
ICD9Proc | - | International Classification of Diseases, Ninth Revision, Clinical Modification, Volume 3 (NCHS)
ATC | - | WHO Anatomic Therapeutic Chemical Classification
Ethnicity | - | OMOP Ethnicity
CPT4 | - | Current Procedural Terminology version 4 (AMA)
HCPCS | - | Healthcare Common Procedure Coding System (CMS)
CMS Place of Service | - | Place of Service Codes for Professional Claims (CMS)
Currency | - | International Currency Symbol (ISO 4217)
Medicare Specialty | - | Medicare provider/supplier specialty codes (CMS)
Race | - | Race and Ethnicity Code Set (USBC)
ICD9CM | - | International Classification of Diseases, Ninth Revision, Clinical Modification, Volume 1 and 2 (NCHS)
ABMS | - | Provider Specialty (American Board of Medical Specialties)
OMOP Extension | - | OMOP Extension (OHDSI)

</div><p style="caret-color: rgb(255, 255, 255); color: rgb(255, 255, 255); font-family: Helvetica; font-size: 12px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">Please download and load the Standardized Vocabularies as following:</p><ol style="caret-color: rgb(255, 255, 255); color: rgb(255, 255, 255); font-family: Helvetica; font-size: 12px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><li>Click on this<span class="Apple-converted-space"> </span><a href="https://athena.ohdsi.org/api/v1/vocabularies/zip/36ce00fd-07c4-4609-a36f-63d3000c96d9">link</a><span class="Apple-converted-space"> </span>to download the zip file. Typical file sizes, depending on the number of vocabularies selected, are between 30 and 250 MB.</li><li>Unpack.</li><li>Reconstitute CPT-4. See below for details.</li><li>If needed, create the tables.</li><li>Load the unpacked files into the tables.</li></ol>Link for downloading the Standardized Vocabularies

Vocabularies release version: v5.0 09-SEP-22

ALL Vocabularies:
ICD10CM	-	International Classification of Diseases, Tenth Revision, Clinical Modification (NCHS)
NUCC	-	National Uniform Claim Committee Health Care Provider Taxonomy Code Set (NUCC)
Revenue Code	-	UB04/CMS1450 Revenue Codes (CMS)
LOINC	-	Logical Observation Identifiers Names and Codes (Regenstrief Institute)
SNOMED	-	Systematic Nomenclature of Medicine - Clinical Terms (IHTSDO)
Gender	-	OMOP Gender
NDC	-	National Drug Code (FDA and manufacturers)
RxNorm Extension	-	RxNorm Extension (OHDSI)
SPL	-	Structured Product Labeling (FDA)
RxNorm	-	RxNorm (NLM)
ICD9Proc	-	International Classification of Diseases, Ninth Revision, Clinical Modification, Volume 3 (NCHS)
ATC	-	WHO Anatomic Therapeutic Chemical Classification
Ethnicity	-	OMOP Ethnicity
CPT4	-	Current Procedural Terminology version 4 (AMA)
HCPCS	-	Healthcare Common Procedure Coding System (CMS)
CMS Place of Service	-	Place of Service Codes for Professional Claims (CMS)
Currency	-	International Currency Symbol (ISO 4217)
Medicare Specialty	-	Medicare provider/supplier specialty codes (CMS)
Race	-	Race and Ethnicity Code Set (USBC)
ICD9CM	-	International Classification of Diseases, Ninth Revision, Clinical Modification, Volume 1 and 2 (NCHS)
ABMS	-	Provider Specialty (American Board of Medical Specialties)
OMOP Extension	-	OMOP Extension (OHDSI)
Please download and load the Standardized Vocabularies as following:

Click on this [link](https://athena.ohdsi.org/api/v1/vocabularies/zip/XXX) to download the zip file. Typical file sizes, depending on the number of vocabularies selected, are between 30 and 250 MB.
Unpack.
Reconstitute CPT-4. See below for details.
If needed, create the tables.
Load the unpacked files into the tables.
```

One question is how long they persist the link.

**Comment by xborrat** [comment]
Sorry for my short knowledge, is this link a call to an API that generates the subset of the mega dictionary? In this case we can create a user friendly function that can call the API with user selected option. But because we have to wait a certain time until we get the mail I guess that using the check box they create a customized database and then they send the link.

**Comment by tompollard** [comment]
@xborrat not sure quite how it works! We should post a message on the forum. I think this is a good way of finding out whether there is broader interest in the tool too.

**Comment by tompollard** [comment]
See: https://forums.ohdsi.org/t/building-a-python-package-to-batch-map-using-omop-dictionary/17466 for Xavi's post and the response/s.

**Comment by xborrat** [comment]
As OMOP experts suggested, we opt to prompt the user to input the URL the user obtained after requesting it from Athena.
See pull request #10.

**Comment by tompollard** [comment]
Andrew Williams suggested looking at Perseus: https://github.com/OHDSI/Perseus

**Comment by xborrat** [comment]
That is a fascinating tool, Tom. As far as I have seen, this is the definitive OMOPization tool. The code mapping part works as coder: from text to concept_id. And this is useful to map from any concept(text) to concept_id(omop code).  Not sure if it covers mapping from one standard vocabulary(code) to another standard vocabulary(code).

**Comment by tompollard** [comment]
@xborrat I haven't checked (and I might well be wrong!) but my understanding was that the open source vocabularies are included in the repository somewhere. I'll take a look later today.

**Comment by tompollard** [comment]
Oh yep, you're right! I'll keep this issue open until we have implemented the same approach in this codebase.

**Comment by tompollard** [comment]
Sorry @xborrat, I see it now.
